name: CRLF Phobia

on:
  push:

jobs:
  main:
    name: NO CRLF
    runs-on: ubuntu-latest

    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2
      - name: Add CRLF-Phobia
        run: yarn add crlf-phobia
      - name: Run CRLF-Phobia
        run: yarn crlf-phobia *
